



@startuml Domain Model
  object Admin{
    String email;
    String firstName;
    String lastName
    String password;
  }

    object Customer{
    String name;
    String email;
    String address;
    int postalCode;
    String town;
    String phoneNumber;
    CustomCarportInquiry customCarportInquiry;
  }
  Customer "1" *-- "1" CustomCarportInquiry

  object CustomCarportInquiry{
    LocalDate inquiryDate;
    CarportDesciption carportDesciption;
    PartList partList;
    double price;
    String status;
  }
  CustomCarportInquiry "1" *-- "1" CarportDesciption
  CustomCarportInquiry "1" *-- "0..1" PartList

  object CarportDesciption{
    double height;
    double width;
    double length;
    RoofDesciption roofDesciption;
    FloorDesciption floorDesciption;
    ToolshedDesciption toolshedDesciption;
    String basicDesciption;
  }
  CarportDesciption "1" *-- "1" RoofDesciption
  CarportDesciption "1" *-- "1" FloorDesciption
  CarportDesciption "1" *-- "0..1" ToolshedDesciption

  object RoofDesciption{
    int angle;
    String material;
    double pricePrM2;
  }

  object FloorDesciption{
    String material;
    double pricePrM2;
  }

  object ToolshedDesciption{
    double height;
    double width;
    double length;
    double pricePrM2;
  }

  object PartList{
    ArrayList<CarportPart> CarportParts;
  }
  PartList "1" o-- "many" CarportPart

  object CarportPart{
    Product product;
    int amount;
    double neededLength;
    String desciption;
  }
  CarportPart o-- Product

  object Product{
    int productId;
    String unit;
    double price;
  }
@enduml

' Aggregation o-- (Is a) Is not responsible for the lifespan of the other class
' Composition *-- (Has a) Responsible for the lifespan of the other class
' Extention <|-- (Extends) 
' Number "n"